#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - wheel

users:
  - name: dev
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA0OI37fIwElQMqZeoymVV+FkG3DbtP3Ch2FuC00DXEr3PYg0dY0McbehukOKRdivcCiIjDKa3iBio0hlE9IXqaes1KaTNsLIncBwfEkgfxh49X1jiVIPDXQWV4zVIeVwAsgS922L7K83OWFHcYMRZnnJ/zqC183+GPvjCmy8zavf0K6yngIn13/5gFtJXhdqORr8jeZXx6cINSY31c6bjFtkBY7gAtTIAkEgJLEzP6Nvi3D45FmeIDvXT5RY1IsIGi9FfEAJE7EzVxhMxYsjhAKsIAetvlh9vQEF6N4tX3bVNgnueEBggiFOP5QII+raGTCl7+H3qHz/dirDOkld1 carellano@Admins-MacBook-Pro.local
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
  - path: /etc/ssh/sshd_config
    content: |
      PermitRootLogin no

packages:
  - curl

cloud_config_modules:
  - runcmd

cloud_final_modules:
  - scripts-user

runcmd:
  - [mkdir, /home/dev/frontend]
  - mkdir /home/dev/backend
