#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - wheel
disable_root: true
users:
  - name: ${user}
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ${init_ssh_public_key}
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
# write_files:
#   - path: /etc/ssh/sshd_config
#     content: |
#       PermitRootLogin no

packages:
  - curl

cloud_config_modules:
  - runcmd

cloud_final_modules:
  - scripts-user

runcmd:
  - mkdir /home/${user}/frontend
  - mkdir /home/${user}/backend
  - systemctl reload sshd
